---
title: "Lesson 5"
output: html_document
---


## Basics of numerical mathematics

- [IEEE 754 Floating point](https://en.wikipedia.org/wiki/IEEE_754)
  - The worst possible way to represent reals (except all the others we tried)
  - Sign, exponent, Mantissa
  - Special values: +/-Inf, NaN
  - Signed zero
    $x = y \centernot\implies \frac{1}{x} = \frac{1}{y}$
  - [Subnormal/Denormals](https://en.wikipedia.org/wiki/Subnormal_number)
    - The subnormal floats are a linearly spaced set of values, which span the gap between the negative and positive normal floats. 
  - A nice playground:https://float.exposed/
- Small value + large value -> lost precision
- Much more precision around 0 than around 1
- Special functions
  - `log1p`, `log1p_exp`, `log_sum_exp`, `log_diff_exp`

## Ordinal models

- Nice, thorough introduction: Bürkner & Vuorre 2019, https://doi.org/10.1177/2515245918823199
- What are ordinal data
- Cumulative model
  - In Stan: [`ordered_logistic`](https://mc-stan.org/docs/functions-reference/bounded_discrete_distributions.html#ordered-logistic-distribution) function, see also the [user's guide section](https://mc-stan.org/docs/stan-users-guide/regression.html#ordered-logistic.section)
- Choice of link function
- Continuation/stop models
- Differences mainly theoretical
